run-title: smollm2-360m-baseline-dense-v2-1

resume: False 
resume-path: smollm2-360m-baseline-dense-1/checkpoint-29355
model: smollm2-baseline-360m

dataset: tuluv3-plus-experts # {experts, tuluv3, medical-sft}
base-model: HuggingFaceTB/SmolLM2-360M
tokenizer: HuggingFaceTB/SmolLM2-360M-Instruct
mask-input: True
save-steps: 0.25
gradient-checkpointing: False
max-length: 8192
random-labels: false

trainable:
  - model

num-epochs: 1
batch-size: 2
gradient-accumulation-steps: 4
learning-rate: 2.e-5
warmup-ratio: 0.03
lr-scheduler: cosine

save-path: ./ckpts