run-title: llama-mob-3b-1

resume: False 
resume-path: ./ckpts
model: llama-mob
random-labels: False

dataset: tuluv3-plus-experts # {experts, tuluv3, medical-sft}
base-model: meta-llama/Llama-3.2-3B
tokenizer: meta-llama/Llama-3.2-3B-Instruct
num-experts: 4
top-k-experts: 1
jitter-noise: 0
router-aux-loss-coef: 0.000
use-load-balancing: False
use-router: True
mask-input: True
max-length: 8192
save-steps: 0.25
gradient-checkpointing: True

trainable:
  - model
  - experts-router
  - experts

num-epochs: 1
batch-size: 1
gradient-accumulation-steps: 8
learning-rate: 2.e-5
warmup-ratio: 0.03
lr-scheduler: cosine

save-path: ./ckpts