run-title: micro-olmo-general-1

resume: False 
resume-path: ./ckpts
model: micro-olmo
random-labels: True

dataset: experts # {experts, finetuning, fineweb-edu, tulu-v2-sft-mixture}
base-model: allenai/OLMo-2-0425-1B
tokenizer: allenai/OLMo-2-0425-1B-Instruct
num-experts: 4
top-k-experts: 1
stage-2-top-k-experts: 2
jitter-noise: 0
use-router: True
mask-input: True
max-length: 4096
save-steps: 0.25

trainable:
  - model

num-epochs: 2
batch-size: 1
gradient-accumulation-steps: 8
learning-rate: 1.e-5
warmup-ratio: 0.03
lr-scheduler: cosine

save-path: ./ckpts